enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include("core")
include("htmx")
include("ktor:core")
include("ktor:htmx")
include("spring:core")
include("spring:htmx")
include("playground")
include("website")