name: "Create release"
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Release tag
        required: true

jobs:
  build-website-image:
    name: Build and publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Export release version
        run: export RELEASE_VERSION=${{ github.event.tag }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build core
        run: ./gradlew :core:publishToSonatype
