name: "Create release"
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Release tag
        required: true

jobs:
  build-website-image:
    name: Build and publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Create gradle dir
        run: mkdir ~/.gradle

      - name: Create gpg file
        run: echo "${{ secrets.GPG_KEY }}" > ~/.gradle/gpg.gpg

      - name: Create gradle dir
        run: |
          echo <<EOF "
          signing.keyId=${{ secrets.GPG_ID }}
          signing.password=${{ secrets.GPG_PASSWORD }}
          signing.secretKeyRingFile=~/.gradle/gpg.gpg
          "
          EOF > ~/.gradle/gradle.properties

      - name: Export release version
        run: export RELEASE_VERSION=${{ github.event.tag }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build core
        run: ./gradlew :core:publishToSonatype
