name: "Create release"
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Release tag
        required: true

jobs:
  build-website-image:
    name: Build and publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

#      - name: Publish libraries
#        run: |
#          ./gradlew :core:publish
#          ./gradlew :htmx:publish
#          ./gradlew :spring:core:publish
#          ./gradlew :spring:htmx:publish
#          ./gradlew :core:jreleaserFullRelease
#          ./gradlew :htmx:jreleaserFullRelease
#          ./gradlew :spring:core:jreleaserFullRelease
#          ./gradlew :spring:htmx:jreleaserFullRelease
#        env:
#          RELEASE_VERSION: ${{ github.event.inputs.tag }}
#          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
#          GPG_KEY: ${{ secrets.GPG_KEY }}
#          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Build libraries
        run: |
          ./gradlew assemble
        env:
          RELEASE_VERSION: ${{ github.event.inputs.tag }}

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.tag }}

      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*/build/libs/*.jar"
          bodyFile: "changelog.md"
          tag: ${{ github.event.inputs.tag }}
