name: "Create release"
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Release tag
        required: true

jobs:
  build-website-image:
    name: Build and publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Publish libraries
        run: |
          ./gradlew :core:publishToSonatype
          ./gradlew :htmx:publishToSonatype
          ./gradlew :spring:core:publishToSonatype
          ./gradlew :spring:htmx:publishToSonatype
        env:
          RELEASE_VERSION: ${{ github.event.tag }}
          GPG_ID: ${{ secrets.GPG_ID }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
